update some of my parts
awkless/chip-8 pull request #24
Opened 2023-03-29 01:28 UTC by l3naz

# Description

What do your changes do?

# Area of Effect

What section of the code base does your changes effect?

2023-03-29 01:30 UTC, l3naz commented
Just update some of my part

2023-03-30 02:27 UTC, awkless requested changes
You have a syntax error at line 63. Plus, you are missing your implementation of opcode 8XY5.

2023-03-30 02:27 UTC, awkless commented on src/core/opcode.c
> +	if (cpu->v[x] == cpu->cpu.v[y])
Syntax error.

You meant to type:

```
if (cpu->v[x] == cpu->v[y])
```

2023-03-31 15:21 UTC, awkless requested changes
You have a syntax error on line 63, you have a left over parenthesis.

2023-03-31 15:21 UTC, awkless commented on src/core/opcode.c
> +	if (cpu->v[x] == cpu->v[y]))
You have a left over parenthesis.

2023-03-31 15:23 UTC, awkless requested changes

2023-03-31 15:23 UTC, awkless commented on src/core/opcode.c
> +	tmp = cpu->v[x] + cpu->v[y];
Variable tmp is undeclared. You probably meant:

```
uint16_t tmp = cpu->v[x] + cpu->v[y];
```

2023-04-01 19:54 UTC, awkless requested changes
Your implementation of opcode 8XY5 does not properly set the VF register. You need to set the VF register to true if __no__ underflow (borrow) occurs. I recommend doing the following:

```
if (cpu->v[x] > cpu->v[y])
        cpu->v[0x0F] = false; // Borrow occurred, set to false...
else
        cpu->v[0x0F] = true; // No borrow occurred, set to true...
```
Plus, you left the `tmp` variable in your opcode 8XY5 implementation unused. I recommend that you remove it.

2023-04-01 19:54 UTC, awkless commented on src/core/opcode.c
> +	uint16_t tmp = 0;
The `tmp` variable is defined but never used in the scope of this function. I recommend removing it.

2023-04-01 19:54 UTC, awkless commented on src/core/opcode.c
> +	cpu->v[0x0f] = false;
According to the CHIP-8 specification the VF register must be set to true if no borrow occurs.

2023-04-01 19:54 UTC, awkless commented on src/core/opcode.c
> +            cpu->v[0x0f] = true;
According to the CHIP-8 specification the VF register must be set to false in case of borrow, i.e., underflow.

2023-04-01 21:31 UTC, awkless requested changes
You forgot to actually perform the subtraction for opcode 8XY5:

```
cpu->v[x] = cpu->v[x] - cpu->v[y];
```

2023-04-01 21:31 UTC, awkless commented on src/core/opcode.c
> +	}
What happened to the actual subtraction operation?

2023-04-03 18:38 UTC, awkless approved these changes

2023-04-03 18:38 UTC, merged